version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db-1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: planning_poker_tjxp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: planning-poker-backend
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
